import type { ConversationMatch } from '@/lib/xavyr/types'
import { DEFAULT_SUGGESTIONS } from '@/lib/xavyr/knowledge'

const CASUAL_SUGGESTIONS = [
  'Browse collections',
  'Tell me about the brand',
  'How do I order?',
  'What makes thrift special here?',
]

/** Casual, playful, and open-ended pools so visitors can chat beyond strict store Q&A. */
export const BANTER_POOLS: ConversationMatch[] = [
  {
    id: 'yes-ok',
    priority: 7,
    patterns: [/^(yes|yeah|yep|yup|ok|okay|k|sure|alright|cool|nice|great|perfect|got it|understood|sounds good)[\s!.?]*$/i],
    responses: [
      'Perfect. Where should we go next on the site?',
      'Great. Want to browse a collection or walk through checkout?',
      'Cool. I am here if you want directions or shopping tips.',
      'Alright. Pick a suggestion below or ask me anything about MysticalPIECES.',
      'Nice. Tell me what caught your eye and I will point you there.',
      'Got it. Shop, cart, delivery, or style philosophy: your call.',
    ],
    suggestions: CASUAL_SUGGESTIONS,
  },
  {
    id: 'no-nope',
    priority: 7,
    patterns: [/^(no|nope|nah|not really|never mind|nevermind|cancel)[\s!.?]*$/i],
    responses: [
      'No problem. We can start fresh whenever you are ready.',
      'All good. Ask when something comes to mind.',
      'Fair enough. I will be here if you change your mind.',
      'Understood. Browse at your pace and ping me if you need a hand.',
      'That is fine. The shop is always a click away when you want it.',
    ],
    suggestions: DEFAULT_SUGGESTIONS,
  },
  {
    id: 'lol-fun',
    priority: 8,
    patterns: [/\b(lol|lmao|haha|hehe|😂|🤣|funny|hilarious)\b/i, /^rofl/i],
    responses: [
      'Glad that landed. Fashion should feel fun too. Want to see what is in the shop?',
      'Ha, fair. I try to keep things light. Anything you want to look at while we are here?',
      'Good energy. MysticalPIECES has plenty of personality in the pieces too. Browse when you are ready.',
      'I hear you. If you want a break from chatting, the Featured section on home is worth a scroll.',
      'Love the vibe. Tell me if you want style tips or a tour of the collections.',
    ],
    suggestions: CASUAL_SUGGESTIONS,
  },
  {
    id: 'bored-entertain',
    priority: 8,
    patterns: [/bored/i, /entertain me/i, /something (fun|interesting)/i, /kill time/i, /pass time/i],
    responses: [
      'Fair. Scroll Featured on the home page for rotating thrift finds, or pick a collection and hunt for a gem.',
      'Try the Shop hub moodboards, or tell me a vibe (streetwear, vintage, minimal) and I will suggest a category.',
      'Browse Outerwear or Accessories if you want a quick win. Most pieces are one of a kind, so it feels like a treasure hunt.',
      'Core Rules is a good read if you like style philosophy. Or we can talk through how to build an outfit from thrift.',
      'Window-shop mode: open Tees or Footwear and imagine what you would pair each piece with. I can help with that.',
    ],
    suggestions: ['Browse collections', 'Read Core Rules', 'Featured on home'],
  },
  {
    id: 'compliment',
    priority: 8,
    patterns: [
      /\b(you're|you are|ur) (cool|awesome|great|helpful|smart|nice|amazing|the best|fun|funny|sweet)\b/i,
      /love you/i,
      /good (job|bot|guide|assistant)/i,
      /well done/i,
    ],
    responses: [
      'That is kind of you. I am glad I can help. What would you like to explore next?',
      'Thank you. I enjoy guiding people around MysticalPIECES. Need a link or a how-to?',
      'Appreciate that. Let me return the favor: tell me what you are shopping for.',
      'You made my day. Now let us find you something good in the catalog.',
      'Means a lot. I am here for directions, style context, and checkout questions anytime.',
    ],
    suggestions: CASUAL_SUGGESTIONS,
  },
  {
    id: 'identity-ai',
    priority: 9,
    patterns: [
      /\b(are you (a )?(real|human|ai|robot|bot|machine|gpt|chatgpt))\b/i,
      /who (made|built|created) you/i,
      /what are you\b/i,
    ],
    responses: [
      'I am Xavyr, the MysticalPIECES site guide. I am built to help you shop and navigate, not to replace the human team behind the brand.',
      'Think of me as a knowledgeable friend who knows this website inside out. Real people run the store; I help you find your way.',
      'I am software, yes, but my job is simple: make this boutique easy to explore. Ask me anything public about the site.',
      'Xavyr is my name. I live on this site to answer shopper questions. For personal help, the team is on email and WhatsApp too.',
      'I am an guide, not a person, but I take the job seriously. Store questions, navigation, style context: that is my lane.',
    ],
    suggestions: ['Who is MysticalPIECES?', 'Contact the store', 'Browse collections'],
  },
  {
    id: 'jazz-chat',
    priority: 6,
    patterns: [
      /just (chat|talk|vibing|hanging)/i,
      /let's (chat|talk|vibe)/i,
      /keep me company/i,
      /nothing much/i,
      /not much/i,
      /chilling/i,
    ],
    responses: [
      'I am down to chat. MysticalPIECES is about conscious style and one-of-a-kind finds. What kind of look are you into lately?',
      'Sure, we can take it easy. Thrift is basically storytelling with fabric. Any era or aesthetic you gravitate toward?',
      'Company accepted. While we are here, want a quick tour of categories or the brand story on About Us?',
      'Chill mode on. If fashion comes up: most pieces here are unique, so finding something that feels like you is part of the fun.',
      'Happy to hang. Ask me random store questions, style thoughts, or where to click next. No rush.',
    ],
    suggestions: CASUAL_SUGGESTIONS,
  },
  {
    id: 'style-chat',
    priority: 7,
    patterns: [
      /\b(outfit|style|fashion|wear|dress|look good|what should i wear|styling|aesthetic|vibe)\b/i,
      /help me (look|dress|style)/i,
    ],
    responses: [
      'Start with one statement piece from the shop, then build around it. Thrift rewards bold choices because pieces are unique.',
      'Core Rules on this site talks about colour with intention and elegance over price tags. Worth a read if you want philosophy, not just clothes.',
      'Pick a category that matches your mood: Outerwear for structure, Tees for casual layers, Accessories to finish the look.',
      'Unique thrift means you are not copying a mannequin. Choose what feels like you, then check size and condition in Quick View.',
      'If you tell me the occasion (casual, night out, work), I can point you to a collection to start browsing.',
    ],
    links: [
      { label: 'Core Rules', href: '/core-rules' },
      { label: 'Shop', href: '/sections/shop' },
    ],
    suggestions: ['Shirts', 'Outerwear', 'Accessories'],
  },
  {
    id: 'joke-request',
    priority: 6,
    patterns: [/tell me a joke/i, /make me laugh/i, /say something funny/i],
    responses: [
      'Why did the thrift jacket apply for a job? It already had great experience. Want to see our Outerwear collection for real?',
      'I would tell you a fashion pun, but I do not want to belt it out. Tees collection might have something louder anyway.',
      'My best joke: paying full fast-fashion price when curated thrift exists. Browse the shop and beat the punchline.',
      'What do you call a unique piece that only one person can buy? Tuesday inventory at MysticalPIECES. Check Featured on home.',
      'I am better at links than stand-up. Try Core Rules for elegant humour in prose instead.',
    ],
    suggestions: ['Browse collections', 'Open Shop'],
  },
  {
    id: 'opinion',
    priority: 6,
    patterns: [/what do you think/i, /your opinion/i, /do you like/i, /what's your take/i],
    responses: [
      'I think conscious thrift with personality beats disposable trends. That is the spirit behind MysticalPIECES.',
      'My take: one great unique piece beats a closet of copies. This store is built around that idea.',
      'I like when people treat clothes as expression, not uniform. Core Rules captures that mindset well.',
      'Honest opinion: hunt slowly, try combinations in your head, and grab what feels unmistakably yours.',
      'I am biased toward this boutique, but the curation and one-of-a-kind stock are genuinely special.',
    ],
    links: [{ label: 'About Us', href: '/about-us' }],
    suggestions: CASUAL_SUGGESTIONS,
  },
  {
    id: 'emoji-only',
    priority: 5,
    patterns: [
      /^[👍👋🔥✨💯😊🙂😎🙏❤💜🖤🤍🛍👔👗]+$/,
      /^(nice|cool|fire|lit)[\s!.?]*$/i,
    ],
    responses: [
      'I see the energy. Want to browse shop or need directions somewhere?',
      'Love it. Tell me in words when you are ready, or tap a suggestion below.',
      'Good vibes. MysticalPIECES has plenty of those in the racks too.',
      'Noted. I am here when you want to talk shop or style.',
      'Solid. Pick a topic below if you want to keep going.',
    ],
    suggestions: DEFAULT_SUGGESTIONS,
  },
  {
    id: 'random-gibberish',
    priority: 4,
    patterns: [/^(asdf|test|testing|123|abc|qwerty|hello world)[\s!.?]*$/i, /^[a-z]{1,3}$/i],
    responses: [
      'Looks like a test message. I am working. Try asking about shop, cart, or delivery.',
      'I am here and listening. When you are ready, ask something about MysticalPIECES.',
      'Got a ping. If you were checking whether I respond: yes. How can I help?',
      'All systems go on my end. What would you like to know about the store?',
      'Message received. Pick a suggestion or type a real question whenever you like.',
    ],
    suggestions: DEFAULT_SUGGESTIONS,
  },
  {
    id: 'miss-you',
    priority: 7,
    patterns: [/miss you/i, /where were you/i, /you left/i, /come back/i],
    responses: [
      'I am still here on the site whenever you need me. What can I help with today?',
      'Never far. Open me anytime for navigation or shopping questions.',
      'Back now. Let us pick up where you left off.',
      'I do not wander off. Ask away when something comes to mind.',
    ],
    suggestions: DEFAULT_SUGGESTIONS,
  },
  {
    id: 'food-music-offtopic-light',
    priority: 4,
    patterns: [
      /\b(pizza|food|eat|hungry|coffee|music|song|artist|movie|netflix|game)\b/i,
    ],
    responses: [
      'That sounds good. I am more of a wardrobe guide than a food critic, but I can help you shop when you are done.',
      'Nice. If you want a fashion break later, Featured on home always has something fresh.',
      'I will leave that topic to you. When fashion calls, MysticalPIECES is here.',
      'Ha, fair. Come back to me when you want thrift picks or checkout help.',
      'Not my specialty, but I enjoy the chat. Store questions are where I shine.',
    ],
    suggestions: CASUAL_SUGGESTIONS,
  },
  {
    id: 'uganda-local',
    priority: 7,
    patterns: [/\b(uganda|kampala|entebbe|jinja|ugx|shilling|matooke|boda)\b/i],
    responses: [
      'MysticalPIECES is based in Kampala, Uganda. Delivery within Kampala is free; outside Kampala has a fee at checkout.',
      'We serve shoppers in Kampala and beyond. Choose your delivery zone at checkout for accurate fees.',
      'Kampala shoppers get free delivery. Wider Uganda is covered too with a transport fee shown before you confirm.',
      'Local and proud. Cash on delivery works well here: you pay when the order arrives.',
      'If you are in Kampala, checkout is straightforward. Outside the city, pick Outside Kampala and enter your area clearly.',
    ],
    links: [{ label: 'Checkout', href: '/checkout' }],
    suggestions: ['Delivery & payment', 'Contact the store'],
  },
  {
    id: 'sustainability',
    priority: 7,
    patterns: [/\b(sustainable|sustainability|eco|environment|secondhand|preloved|reuse|recycle|green)\b/i],
    responses: [
      'Thrift is slow fashion by nature: fewer new resources, more life in each garment. MysticalPIECES curates pieces meant to be worn and kept.',
      'Choosing secondhand is one of the kindest things you can do for your wardrobe and the planet. We lean into that with every collection.',
      'Most items here are preloved or vintage-inspired finds. Unique stock means less mass production, more individuality.',
      'Conscious style is in the brand DNA. About Us and Core Rules both touch on intention over waste.',
    ],
    links: [
      { label: 'About Us', href: '/about-us' },
      { label: 'Core Rules', href: '/core-rules' },
    ],
    suggestions: ['Browse collections'],
  },
  {
    id: 'price-budget',
    priority: 7,
    patterns: [/\b(cheap|expensive|afford|budget|price|prices|cost|how much|ugx)\b/i],
    responses: [
      'Prices are shown on each product card and in Quick View. Because most pieces are unique thrift, values vary by item.',
      'Thrift here is about value and character, not fast-fashion churn. Browse a category to see what is in stock now.',
      'I cannot quote every price from memory, but the catalog is live. Search or open a collection to compare.',
      'Cash on delivery means you see what you ordered before you pay. Check individual listings for exact amounts.',
    ],
    links: [{ label: 'Shop', href: '/sections/shop' }],
    suggestions: ['Browse collections'],
  },
  {
    id: 'frustration-support',
    priority: 12,
    patterns: [
      /\b(frustrated|annoyed|angry|upset|doesn't work|not working|broken|bug|issue|problem)\b/i,
      /why won't/i,
    ],
    responses: [
      'Sorry that is frustrating. Tell me what you were trying to do (checkout, login, find a product) and I will walk you through it.',
      'Let us fix it step by step. Which page are you on and what happened when you clicked?',
      'I want to help. Common fixes: fill all checkout fields, refresh the page, or try signing in again for account issues.',
      'If it is order-related, contact the team on email or WhatsApp with your order details. I can share those links.',
      'That sounds rough. Describe the step where it stuck and I will suggest the next move.',
    ],
    links: [{ label: 'Contact', href: '/#contact' }],
    suggestions: ['How do I order?', 'Sign in / Register', 'Contact the store'],
  },
  {
    id: 'night-morning',
    priority: 6,
    patterns: [/good night/i, /good morning/i, /good afternoon/i, /good evening/i],
    responses: [
      'Good day to you too. MysticalPIECES is open online whenever you are.',
      'And to you. Happy browsing whenever the mood strikes.',
      'Likewise. I am here if you need store help today.',
      'Warm greetings. Tell me what you want to find and we will get started.',
    ],
    suggestions: DEFAULT_SUGGESTIONS,
  },
  {
    id: 'who-is-ceo',
    priority: 7,
    patterns: [/\b(ceo|founder|lrba|dingwa|jerry|owner|who runs)\b/i],
    responses: [
      'LRBA (Dingwa) founded MysticalPIECES with a vision for conscious, future-facing thrift. The CEO Profile page tells more of that story.',
      'The brand was built around curated thrift and individuality. About Us and CEO Profile share the people side of the story.',
      'Dingwa leads with a passion for unique finds and sustainable style. Visit CEO Profile for the full background.',
    ],
    links: [
      { label: 'CEO Profile', href: '/ceo-profile' },
      { label: 'About Us', href: '/about-us' },
    ],
  },
]
